server:
    error:
        include-exception: false
        include-message: always
        include-stacktrace: on_param

spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/basic
        username: sa
        password:
        driver-class-name: org.h2.Driver
    
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            # show_sql: true
            format_sql: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


template:
    app:
        jwtSecret: templateSecretKey
        jwtExpirationMs: 86400000